# Generated by Django 5.2.13 on 2026-04-18 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_chatmessage_attachment_interviewrequest_feedback_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='news/')),
                ('kind', models.CharField(choices=[('image', 'Изображение'), ('video', 'Видео')], default='image', max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='production.newspost')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
