# Generated by Django 5.2.13 on 2026-04-18 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0005_newsmedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
