# Generated by Django 5.2.13 on 2026-04-22 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0006_newspost_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cover_image',
            field=models.FileField(blank=True, null=True, upload_to='order_covers/'),
        ),
    ]
